# -*- coding: utf-8 -*-
"""LABORATÓRIO VIRTUAL DE APOIO AO ENSINO DE ELETROFISIOLOGIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkYhIWph4R_3I7BV9VlaJpNkmFbY5Dzk

# <center>LABORATÓRIO VIRTUAL DE APOIO AO ENSINO DE ELETROFISIOLOGIA</center>
"""

Nome = '' #@param {type:"string"}
Curso = '' #@param {type:"string"}
Data = '2019-10-07' #@param {type:"date"}

"""<div><center> <img src=https://cf-users.mindthegraph.com/creations/creation_70473/preview_152.png> </center></div>


## <center>  Seja bem-vindo ao Laboratório Virtual de Apoio ao Ensino de Eletrofisiologia </center>
\
O objetivo desse objeto de aprendizagem é fornecer à você um **estudo dirigido interativo** contemplando temas relevantes à disciplina de **Eletrofisiologia do Sistema Nervoso Central** e outras semelhantes, tais como **Biofísica** e **Neurofisiologia**.

Você precisará **interagir com essa página** de diversas maneiras, seja através da execução de blocos de código que compõe o documento ou através de botões e ferramentas de visualização de gráficos.

Siga as instruções abaixo para se familiarizar com o ambiente antes de prosseguir. **Você deve estar logado em uma conta Google para interagir com o ambiente.**

Em caso de dúvidas ou problemas em qualquer etapa, mande um email para [negrini.guilherme@gmail.com](mailto:negrini.guilherme@gmail.com)

Bom estudo!

## <center> Instruções </center>

### **Abrindo o objeto e salvando uma cópia**
Para utilizar o objeto de aprendizagem e salvar o resultado das suas atividades clique, no menu superior, em ***File*** e depois em ***Save a copy in Drive***. Uma nova janela será aberta e você deve utilizar o objeto aberto nela, dessa forma seu arquivo será salvo no seu próprio Google Drive.

\

### **Executando blocos**
Quando for solicitado que **"execute um bloco"**, siga os passos abaixo:

*   Clique em cima do bloco
*   Clique no símbolo de ***Play*** situado no lado esquerdo do bloco ou pressione as teclas ***CTRL+Enter***
*   Observação: você pode executar um bloco quantas vezes quiser, porém isso fará com que ele retorne ao estado inicial. Tome cuidado, pois, no caso de blocos com gráficos, os valores exibidos serão perdidos.


**Teste com os blocos abaixo!**

---
"""

#@title Execute esse bloco

print("Parabéns, você executou esse bloco com sucesso!")

#@title Execute esse bloco mais de uma vez
try:
    num = int(input('Digite um número inteiro e aperte ENTER: '))
    print('Você digitou o número: {}'.format(num))
    print('Observe que esse valor será perdido na próxima execução.')
except ValueError:
    print('Você não digitou um número inteiro, tente novamente.')

"""

---

### **Gráficos interativos**
O gráfico logo abaixo possui alguns elementos de interatividade, observe algumas ferramentas disponíveis na barra lateral direita:
* **Arraste**: ![Arraste](https://bokeh.pydata.org/en/latest/_images/Pan.png)
    * Permite que você navegue pelo gráfico através do arraste pelos eixos.
* **Caixa de zoom**: ![Caixa de Zoom](https://bokeh.pydata.org/en/latest/_images/BoxZoom.png)
    * Permite o zoom em uma área retangular selecionada.
* **Roda de zoom**: ![Roda de Zoom](https://bokeh.pydata.org/en/latest/_images/WheelZoom.png)
    * Permite aumentar ou diminuir o zoom através da roda do mouse.
* **Reset**: ![Reset](https://bokeh.pydata.org/en/latest/_images/Reset.png)
    * Retorna a visualização para os valores iniciais dos eixos.
* **Salvar**: ![Salvar](https://bokeh.pydata.org/en/latest/_images/Save.png)
    * Faz o download da imagem para salvar no seu computardor.
* **Inspeção**: ![Inspeção](https://bokeh.pydata.org/en/latest/_images/Hover.png)
    * Exibe o valor de determinado ponto ao posicionar o cursor do mouse em cima.
    
\



Existem **5 pontos** no gráfico abaixo. **Utilize as ferramentas** de arraste (já selecionada), roda de zoom e inspeção (já selecionada) para **descobrir os valores de x e y para cada ponto**.

Após, clique no botão "Respostas" e **confira seu resultado**!"""

#@title Execute esse bloco para começar a interagir com o gráfico

from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import TextInput, Dropdown
from bokeh.layouts import row, column
from bokeh.io import output_notebook



source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'B', 'C', 'D', 'E'],
))


plot = figure(y_range=(3, 8), plot_width=400, plot_height=400, tooltips=[("Ponto", "@desc"),("(x, y)", "($data_x, $data_y)")],
           title="Explore as ferramentas", x_axis_label='x',
              y_axis_label='y')

plot.circle('x', 'y', size=10, source=source)

input_A = TextInput(value="(x,y)", title="Ponto A:")
input_B = TextInput(value="(x,y)", title="Ponto B:")
input_C = TextInput(value="(x,y)", title="Ponto C:")
input_D = TextInput(value="(x,y)", title="Ponto D:")
input_E = TextInput(value="(x,y)", title="Ponto E:")

menu = [("Ponto A: (1,2)", "A"), ("Ponto B: (2,5)", "B"), ("Ponto C: (3,8)", "C"), ("Ponto D: (4,2)", "D"), ("Ponto E: (5,7)", "E")]
dropdown = Dropdown(label="Respostas", button_type="success", menu=menu)

layout = row(
    plot,
    column(input_A,input_B,input_C,input_D,input_E),
    dropdown,
)

output_notebook()

show(layout)

"""## <center> Pronto, agora você já está familiarizado com as principais funções do objeto. </center>
## <center>Siga para as atividades abaixo!</center>

---

## Atividade 1 - Potencial de equilíbrio
### Introdução

O potencial de equilíbrio, também conhecido como **potencial de Nernst**, é o potencial de membrana para o qual o **fluxo líquido de determinado íon através da membrana é nulo**. A equação de Nernst define a **diferença de potencial elétrico através da membrana** com relação às concentrações internas e externas de uma espécie iônica quando o equilíbrio é atingido.


**<center> Equação de Nernst</center>**



$$Vm = \frac{RT}{zF}ln\frac{[íon]e}{[íon]i}$$


Onde:


*   R = constante universal dos gases
*   T = temperatura em Kelvin
*   z = valência do íon
*   F = constante de Faraday
*  [íon]e = concentração iônica fora da célula
*  [íon]i = concentração iônica dentro da célula

\
### Exercícios
Abaixo, você encontra um gráfico interativo para a visualização do potencial de equilíbrio de diferentes espécies iônicas.  Use o **menu de escolha** para selecionar a espécie iônica e as **barras deslizantes** para variar as concentrações. Ao posicionar o **mouse em cima de um ponto no gráfico** você verá o valor do potencial.

\

### 1) **Descubra o potencial de equilíbrio** para cada espécie de acordo com os **dados da tabela**.
"""

#@title Execute esse bloco para começar a interagir com o gráfico
import numpy as np
import pandas as pd
import math
import copy
import time

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, Dropdown
from bokeh.io import output_notebook

x = np.linspace(10, 50, 50)
y = copy.copy(x)
x2 = copy.copy(x)
y2 = copy.copy(x)

t_celsius = 37
valence = 1
t_kelvin = t_celsius + 273
r = 8.314
f = 96.485
ion_in = 1
ion_out = 1

div = Div(text="""<br><center><h4>Concentrações de espécies iônicas para neurônios humanos:</h4></center>""",
width=400, height=20)

df = pd.DataFrame({'ion': ['Na+', 'K+', 'Cl-'], 'ion_e' : [150, 5, 150], 'ion_i' : [15, 100, 13]}, index=None)

source_table = ColumnDataSource(df)

columns = [
        TableColumn(field="ion", title="Espécie iônica"),
        TableColumn(field="ion_e", title="[íon]externa (mM)"),
        TableColumn(field="ion_i", title="[íon]interna (mM)"),
    ]
data_table = DataTable(source=source_table, columns=columns, width=400, height=100, editable=True)

datahora2=int(time.time());

for i in range(len(x)):
    y[i] = ((2.303*((r*t_kelvin)/(valence*f))*math.log10((ion_out/ion_in))))
    y2[i] = ((2.303*((r*t_kelvin)/(valence*f))*math.log10((ion_out/ion_in))))


source = ColumnDataSource(data=dict(x=x, y=y,x2=x2,y2=y2))

plot = figure(y_range=(-100, 100), plot_width=400, plot_height=400,
              tools=["pan,wheel_zoom,box_zoom,reset,save", HoverTool(names=['pontos'], tooltips=[("Potencial", "$data_y")])],
              title="Potencial de equilíbrio",
              x_axis_label='Tempo (u.a.)',
              y_axis_label='Potencial (mV)')

plot.line('x', 'y', name='linhas', source=source, line_width=3, line_alpha=0.6)
plot.scatter('x', 'y', name='pontos', size=5, source=source)


ion_e_slider = Slider(start=1, end=200, value=1, step=1, title="[íon]externa (mM)")
ion_i_slider = Slider(start=1, end=200, value=1, step=1, title="[íon]interna (mM)")
ion_select = Select(title="Espécie iônica", value="1", options=[("1", "Na+"), ("1", "K+"),("-1", "Cl-")] )

callback = CustomJS(args=dict(source=source, ion_e=ion_e_slider, ion_i=ion_i_slider,datahora2=datahora2, ion_s=ion_select),
                    code="""
    var data = source.data;
    const ioni = ion_i.value;
    const ione = ion_e.value;
    const valence = ion_s.value;
    const t_celsius = 37;
    const t_kelvin = t_celsius + 273;
    const r = 8.314;
    const f = 96.485;
    var x = data['x'];
    var y = data['y'];
    var x2 = data['x2'];
    var y2 = data['y2'];
    var datahoraaux = Math.round(Number(Date.now())/1000);
    var dh2 = datahora2;
    var datahora = datahoraaux - dh2;
    var flag = true;

    const vm = ((2.303*((r*t_kelvin)/(valence*f))*Math.log10((ione/ioni))))

    if (vm != y[0] ){
        dh2 = Math.round(Number(Date.now())/1000);
        for (var i = 1; i < (x.length); i++) {
            y[i] =(y2[i-1]);
            x[i] =(x2[i-1])+datahora;
        }
    }

    y[0]=vm;
    x[0]= 0;

    for (var i = 0; i < (x.length); i++) {
        x2[i]=x[i];
        y2[i]=y[i];
    }
    source.change.emit();

""")


ion_i_slider.js_on_change('value', callback)

ion_e_slider.js_on_change('value', callback)

ion_select.js_on_change('value', callback)

menu = [("Na+: 61.519 mV", "Na"), ("K+: -80.037 mV", "K"), ("Cl-: -65.342 mV", "Cl")]
dropdown = Dropdown(label="Respostas", button_type="success", menu=menu)

layout = row(
    column(plot, width=420),
    column(ion_select,ion_e_slider,ion_i_slider, div, data_table, sizing_mode='scale_width', width=420),
    column(dropdown),
)

output_notebook()

show(layout)

"""### Clique duas vezes aqui para escrever sua resposta ou suas observações!
R:

---



### 2) O ***tamponamento espacial de potássio (K+)*** é um processo de controle da concentração extracelular desse íon realizado pelos **astrócitos**. Aumente a concentração extracelular de K+ (mantendo a concentração interna fisiológica) e **observe o que acontece com o potencial de equilíbrio**. **Discuta as possíveis consequências** para a célula e a **importância do tamponamento** realizado pelos astrócitos.
"""

#@title Execute esse bloco para começar a interagir com o gráfico
import numpy as np
import pandas as pd
import math
import copy
import time

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, Dropdown
from bokeh.io import output_notebook

x = np.linspace(10, 50, 50)
y = copy.copy(x)
x2 = copy.copy(x)
y2 = copy.copy(x)

t_celsius = 37
valence = 1
t_kelvin = t_celsius + 273
r = 8.314
f = 96.485
ion_in = 1
ion_out = 1

div = Div(text="""<br><center><h4>Concentrações de espécies iônicas para neurônios humanos:</h4></center>""",
width=400, height=20)

df = pd.DataFrame({'ion': ['Na+', 'K+', 'Cl-'], 'ion_e' : [150, 5, 150], 'ion_i' : [15, 100, 13]}, index=None)

source_table = ColumnDataSource(df)

columns = [
        TableColumn(field="ion", title="Espécie iônica"),
        TableColumn(field="ion_e", title="[íon]externa (mM)"),
        TableColumn(field="ion_i", title="[íon]interna (mM)"),
    ]
data_table = DataTable(source=source_table, columns=columns, width=400, height=100, editable=True)

datahora2=int(time.time());

for i in range(len(x)):
    y[i] = ((2.303*((r*t_kelvin)/(valence*f))*math.log10((ion_out/ion_in))))
    y2[i] = ((2.303*((r*t_kelvin)/(valence*f))*math.log10((ion_out/ion_in))))


source = ColumnDataSource(data=dict(x=x, y=y,x2=x2,y2=y2))

plot = figure(y_range=(-100, 100), plot_width=400, plot_height=400,
              tools=["pan,wheel_zoom,box_zoom,reset,save", HoverTool(names=['pontos'], tooltips=[("Potencial", "$data_y")])],
              title="Potencial de equilíbrio",
              x_axis_label='Tempo (u.a.)',
              y_axis_label='Potencial (mV)')

plot.line('x', 'y', name='linhas', source=source, line_width=3, line_alpha=0.6)
plot.scatter('x', 'y', name='pontos', size=5, source=source)


ion_e_slider = Slider(start=1, end=200, value=1, step=1, title="[íon]externa (mM)")
ion_i_slider = Slider(start=1, end=200, value=100, step=1, title="[íon]interna (mM)")
ion_select = Select(title="Espécie iônica", value="1", options=[("1", "Na+"), ("1", "K+"),("-1", "Cl-")] )

callback = CustomJS(args=dict(source=source, ion_e=ion_e_slider, ion_i=ion_i_slider,datahora2=datahora2, ion_s=ion_select),
                    code="""
    var data = source.data;
    const ioni = ion_i.value;
    const ione = ion_e.value;
    const valence = ion_s.value;
    const t_celsius = 37;
    const t_kelvin = t_celsius + 273;
    const r = 8.314;
    const f = 96.485;
    var x = data['x'];
    var y = data['y'];
    var x2 = data['x2'];
    var y2 = data['y2'];
    var datahoraaux = Math.round(Number(Date.now())/1000);
    var dh2 = datahora2;
    var datahora = datahoraaux - dh2;
    var flag = true;

    const vm = ((2.303*((r*t_kelvin)/(valence*f))*Math.log10((ione/ioni))))

    if (vm != y[0] ){
        dh2 = Math.round(Number(Date.now())/1000);
        for (var i = 1; i < (x.length); i++) {
            y[i] =(y2[i-1]);
            x[i] =(x2[i-1])+datahora;
        }
    }

    y[0]=vm;
    x[0]= 0;

    for (var i = 0; i < (x.length); i++) {
        x2[i]=x[i];
        y2[i]=y[i];
    }
    source.change.emit();

""")


ion_i_slider.js_on_change('value', callback)

ion_e_slider.js_on_change('value', callback)

ion_select.js_on_change('value', callback)


menu = [("Na+: 61.519 mV", "Na"), ("K+: -80.037 mV", "K"), ("Cl-: -65.342 mV", "Cl")]

layout = row(
    column(plot, width=420),
    column(ion_select,ion_e_slider,ion_i_slider, div, data_table, sizing_mode='scale_width', width=420)
)

output_notebook()

show(layout)

"""### **Clique duas vezes aqui para escrever sua resposta ou suas observações!**
R:

---

## Atividade 2 - Propriedades passivas de membrana
### Constante de tempo
#### Introdução

A membrana plasmática neuronal possui propriedades elétricas passivas facilmente visualizadas em resposta à alterações do potencial de membrana. Analogamente a um circuito elétrico, a membrana plasmática possui um comportamento de **capacitor**, sendo capaz de **armazenar cargas iônicas** nas faces interna e externa separadas pela bicamada lipídica da célula. Além da capacitância, a membrana plasmática neuronal também possui um propriedade resistiva influenciada pelos **canais iônicos** presentes na membrana, os quais constituem um caminho de **passagem de corrente iônica** através das faces.

\
O efeito da passagem de uma corrente através de um circuito composto por componentes resistivos e capacitivos, tal como uma membrana celular, é a alteração de forma **exponencial** do potencial. A **constante de tempo** relaciona os termos capacitivos e resistivos de um circuito e calcula o tempo necessário para a atingir 63% do potencial máximo durante a carga ou decair 37% durante a descarga.



\

**<center> Constante de tempo</center>**



$$\tau = RC$$


Onde:


*   R = resistência da membrana plasmática (ohm)
*   C = capacitância da membrana plasmática (farad)

\
### Exercícios
O gráfico abaixo mostra o registro do potencial de membrana de duas células durante a carga (acensão das curvas até o ponto máximo) e descarga (decaimento das curvas) da membrana. Observe os valores de resistência e capacitância para cada célula:



1.   Célula grande
    - Resistência: $25 \times 10^6 \Omega$
    - Capacitância: $3,14 \times 10^{-14} F \$

\
2.   Célula pequena
    - Resistência: $637 \times 10^7 \Omega$
    - Capacitância: $3,14 \times 10^{-16} F \$

### 1) Calcule a constante de tempo para cada célula e observe no gráfico o valor do potencial medido nesses pontos.
"""

#@title Execute esse bloco para começar a interagir com o gráfico
import numpy as np
from math import e

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, TextInput, Dropdown
from bokeh.io import output_notebook

def charge (t, r, c):
    vo = 80*10**-3
    tau = r*c

    return (vo*(1-e**((-t/tau))))

def discharge (t, r, c):
    tau = r*c
    vo = charge(5*tau, r, c)
    return (vo*(e**((-t/tau))))

# 50uM
r = 25*10**6
c = 3.14*10**-14
tau = r*c

time_up = np.linspace(0, 5*tau, 1000)
time_down = np.linspace(5*tau, 10*tau, 1000)

vc = charge(time_up, r, c)
vc = vc - 0.06
vd = discharge(time_down-5*tau, r, c)
vd = vd - 0.06

time = np.hstack((time_up, time_down))
v = np.hstack((vc,vd))


 #5uM
r2 = 637*10**7
c2 = 3.14*10**-16
tau2 = r2*c2

time_up2 = np.linspace(0, 5*tau2, 1000)
time_down2 = np.linspace(5*tau2, 10*tau2, 1000)

vc2 = charge(time_up2, r2, c2)
vc2 = vc2 - 0.06
vd2 = discharge(time_down2-5*tau2, r2, c2)
vd2 = vd2 - 0.06

v2 = np.hstack((vc2,vd2))

time2 = np.hstack((time_up2, time_down2))


source = ColumnDataSource(data=dict(v=v*10**3, time=time*10**6, v2=v2*10**3, time2=time2*10**6))
#source = ColumnDataSource(data=dict(v=v, time=time, v2=v2, time2=time2))

plot = figure(plot_width=600, plot_height=400,
              tools=["pan,wheel_zoom,box_zoom,reset,save", HoverTool(names=['vc_linha', 'vd_linha','v_linha', 'v2_linha'], tooltips=[("Tempo", "$data_x"),("Potencial", "$data_y")])],
              title="Constante de tempo",
              x_axis_label='Tempo (us)',
              y_axis_label='Potencial (mV)')

plot.line('time', 'v', name='v_linha', source=source, line_width=3, line_color='darkorange',muted_color='orange', muted_alpha=0.1, legend='Célula grande')
plot.line('time2', 'v2', name='v2_linha', source=source, line_width=3, line_color='darkblue',muted_color='blue', muted_alpha=0.1, legend='Célula pequena')
plot.legend.click_policy="mute"

input_celG = TextInput(value="Constante de tempo", title="Célula grande")
input_celP = TextInput(value="Constante de tempo", title="Célula pequena")

menu = [("Célula grande: 0,785 us", "G"), ("Célula pequena: 2,0 us", "P")]
respostas = Dropdown(label="Respostas", button_type="success", menu=menu)

layout = row(column(
    plot), column(input_celG, input_celP, respostas)
)
output_notebook()

show(layout)

"""### Quais as consequências de uma constante de tempo longa durante um registro eletrofisiológico?

### **Clique duas vezes aqui para escrever sua resposta ou suas observações!**
R:

---

## Atividade 3 - Filtros eletrônicos
### Introdução

Filtros eletrônicos são circuitos com a função de selecionar, ou rejeitar, sinais elétricos baseados em uma determinada frequência de corte. Os filtros podem ser classificados conforme o tipo de seleção do sinal:


**1.   Passa-baixa**


> Permite a passagem de sinais de baixa frequência enquanto atenua sinais com frequência acima da frequência de corte.

\
**2.   Passa-alta**
> Permite a passagem de sinais de alta frequência enquanto atenua sinais com frequência abaixo da frequência de corte.

\
**3.   Passa-banda**
> Permite a passagem de sinais de frequência dentro de um determinado intervalo.


\

### Exercícios
O gráfico abaixo mostra um determinado registro de sinais elétricos. Nele podemos observar 3 sinais distintos e o sinal resultante composto pela soma dos 3.


*   Sinal 1
    - Amplitude: 50 mV
    - Frequência: 5 Hz
*   Sinal 2
    - Amplitude: 50 mV
    - Frequência: 10 Hz
*   Sinal 3
    - Amplitude: 25 mV
    - Frequência: 100 Hz

\
### 1) Clique em cada legenda interativa do gráfico (canto superior direito) para visualizar a contribuição de cada sinal para a formação do sinal composto. Observe com atenção as frequências e as amplitudes.
"""

#@title Clique nas legendas para visualizar os diferentes sinais

import numpy as np
from scipy.signal import butter, lfilter, freqz, filtfilt
import matplotlib.pyplot as plt

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, Dropdown
from bokeh.io import output_notebook

# Parâmetros
fs = 500

# Sinais

T = 1             # tempo em segundos
n = int(T * fs)     # número de amostras
t = np.linspace(0, T, n, endpoint=False)

sig1 = 50*np.sin(2*np.pi*5*t)
sig2 = 50*np.sin(2*np.pi*10*t)
sig3 = 25*np.sin(2*np.pi*100*t)
noise_data = sig1+sig2+sig3

source = ColumnDataSource(data=dict(t=t, sig1=sig1, sig2=sig2, sig3=sig3, noise_data=noise_data))

plot_sinais = figure(plot_width=800, plot_height=400,
              tools=["pan,wheel_zoom,box_zoom,reset,save"],
              title="Sinais",
              x_axis_label='Tempo (s)',
              y_axis_label='Amplitude (mV)')


plot_sinais.line('t', 'sig1', name='sinal1', source=source, line_width=2, line_color='red',muted_color='red', muted_alpha=0.1, alpha=0.6,legend='Sinal 1 (5 Hz)', muted=True)
plot_sinais.line('t', 'sig2', name='sinal2', source=source, line_width=2, line_color='green',muted_color='green', muted_alpha=0.1, alpha=0.6,legend='Sinal 2 (10 Hz)', muted=True)
plot_sinais.line('t', 'sig3', name='sinal3', source=source, line_width=2, line_color='blue',muted_color='blue', muted_alpha=0.1, alpha=0.6,legend='Sinal 3 (100 Hz)', muted=True)
plot_sinais.line('t', 'noise_data', name='noise', source=source, line_width=2, line_color='darkorange',muted_color='darkorange', muted_alpha=0.1, alpha=1,legend='Sinal composto')
plot_sinais.legend.click_policy="mute"
layout = column(plot_sinais
)

output_notebook()

show(layout)

"""### 2) Suponha que o sinal 3 seja um ruído de alta frequência presente no registro do sinal composto. Selecione o filtro e a frequência de corte apropriada para atenuar apenas esse sinal.

### **Após selecionar os parâmetros, execute o bloco para atualizar o gráfico.**
"""

Filtro_ = "Passa-baixa" #@param [ "","Passa-baixa", "Passa-alta"]
Frequencia_de_corte = 14 #@param {type:"slider", min:1, max:200, step:1}

import numpy as np
from scipy.signal import butter, lfilter, freqz, filtfilt
import matplotlib.pyplot as plt

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, Dropdown
from bokeh.io import output_notebook


from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, Dropdown
from bokeh.io import output_notebook


# Parâmetros
fs1 = 500
cutoff1 = Frequencia_de_corte
ordem = 6
normal_cutoff = (cutoff1/(0.5*fs1))

# Sinais

T = 1             # tempo em segundos
n = int(T * fs1)     # número de amostras
t = np.linspace(0, T, n, endpoint=False)

sig1a = 50*np.sin(2*np.pi*5*t)
sig2a = 50*np.sin(2*np.pi*10*t)
sig3a = 25*np.sin(2*np.pi*100*t)
noise_data1 = sig1a+sig2a+sig3a

# Coeficientes do filtro
if Filtro_ == 'Passa-baixa':
    b, a = butter(ordem, normal_cutoff, btype='low', analog=False)
    filtrado1 = filtfilt(b, a, noise_data1)
elif Filtro_ == 'Passa-alta':
    b, a = butter(ordem, normal_cutoff, btype='high', analog=False)
    filtrado1 = filtfilt(b, a, noise_data1)
else:
    filtrado1 = noise_data1
    print('Selecione um tipo de filtro e a frequência de corte.')

source1 = ColumnDataSource(data=dict(t=t, sig1a=sig1a, sig2a=sig2a, sig3a=sig3a, noise_data1=noise_data1, filtrado1=filtrado1))

plot_filtro1 = figure(plot_width=800, plot_height=400,
            tools=["pan,wheel_zoom,box_zoom,reset,save"],
            title="Filtro",
            x_axis_label='Tempo (s)',
            y_axis_label='Amplitude (mv)')

plot_filtro1.line('t', 'noise_data1', name='noise', source=source1, line_width=2, line_color='darkorange',muted_color='darkorange', muted_alpha=0.1, alpha=0.7,legend='Sinal composto')
plot_filtro1.line('t', 'filtrado1', name='filtro', source=source1, line_width=2, line_color='red',muted_color='red', muted_alpha=0.1, alpha=1,legend='Sinal filtrado')
plot_filtro1.legend.click_policy="mute"

menu = [("Filtro: passa-baixa", "pb"), ("Frequência de corte: entre 30 Hz e 70 Hz", "fc")]
respostas = Dropdown(label="Respostas", button_type="success", menu=menu)

layout = row(column(plot_filtro1), column(respostas)
)

output_notebook()

show(layout)

"""### 3) Suponha agora que o sinal 3 é o único sinal de interesse para o registro. Selecione o filtro e a frequência de corte apropriada para permitir a passagem apenas desse sinal.
###Após selecionar os parâmetros, execute o bloco para atualizar o gráfico.
"""

Filtro = "" #@param [ "","Passa-baixa", "Passa-alta"]
Frequencia_de_corte = 200 #@param {type:"slider", min:1, max:200, step:1}

import numpy as np
from scipy.signal import butter, lfilter, freqz, filtfilt
import matplotlib.pyplot as plt

from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, Dropdown
from bokeh.io import output_notebook


from bokeh.layouts import row, column
from bokeh.models import CustomJS, Slider, Select, HoverTool
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, Div, TextAreaInput, Dropdown
from bokeh.io import output_notebook


# Parâmetros
fs2 = 500
cutoff2 = Frequencia_de_corte
ordem = 6
normal_cutoff = (cutoff2/(0.5*fs2))

# Sinais

T = 1             # tempo em segundos
n = int(T * fs2)     # número de amostras
t = np.linspace(0, T, n, endpoint=False)

sig1b = 50*np.sin(2*np.pi*5*t)
sig2b = 50*np.sin(2*np.pi*10*t)
sig3b = 25*np.sin(2*np.pi*100*t)
noise_data2 = sig1b+sig2b+sig3b

# Coeficientes do filtro
if Filtro == 'Passa-baixa':
    b, a = butter(ordem, normal_cutoff, btype='low', analog=False)
    filtrado2 = filtfilt(b, a, noise_data2)
elif Filtro == 'Passa-alta':
    b, a = butter(ordem, normal_cutoff, btype='high', analog=False)
    filtrado2 = filtfilt(b, a, noise_data2)
else:
    print('Selecione o tipo de filtro e frequência de corte')
    filtrado2 = noise_data2

source2 = ColumnDataSource(data=dict(t=t, sig1b=sig1b, sig2b=sig2b, sig3b=sig3b, noise_data2=noise_data2, filtrado2=filtrado2))

plot_filtro2 = figure(plot_width=800, plot_height=400,
              tools=["pan,wheel_zoom,box_zoom,reset,save"],
              title="Filtro",
              x_axis_label='Tempo (s)',
              y_axis_label='Amplitude (mV)')

plot_filtro2.line('t', 'noise_data2', name='noise', source=source2, line_width=2, line_color='darkorange',muted_color='darkorange', muted_alpha=0.1, alpha=0.7,legend='Sinal composto')
plot_filtro2.line('t', 'filtrado2', name='filtro', source=source2, line_width=2, line_color='red',muted_color='red', muted_alpha=0.1, alpha=1,legend='Sinal filtrado')
plot_filtro2.legend.click_policy="mute"

menu = [("Filtro: passa-alta", "pa"), ("Frequência de corte: entre 30 Hz e 70 Hz", "fc")]
respostas = Dropdown(label="Respostas", button_type="success", menu=menu)

layout = row(column(plot_filtro2), column(respostas)
)

output_notebook()

show(layout)

"""

---




## <center> Avalie a atividade </center>

\

Muito obrigado por utilizar o Laboratório Virtual de Apoio ao Ensino de Eletrofisiologia!

\
Gostaríamos de solicitar que você respondesse um **breve questionário** sobre essa atividade clicando [aqui](https://forms.gle/nPAaSoUoScUdCMLF8).

"""